Этап 1 - v.1
bmv-git/bruno-go-market pull request #1
Opened 2024-04-22 14:58 UTC by bmv-git

request for review

2024-04-22 15:39 UTC, artemovechkin requested changes

2024-04-22 15:39 UTC, artemovechkin commented on Internal/core/interface.go
> +}
в рамках объема этого проекта, можно обойтись чтобы не усложнять и не придумывать применения их там, где нет необходимости

2024-04-22 15:39 UTC, artemovechkin commented on Internal/handlers/products.go
> +
делая это обращения горутиной, теряем возможность узнать об ошибке записи в базу данных + не увидел select и место где встаем на блокировку по каналам

 рекомендую оставить последовательным выполнение данного роута, не понядобятся каналы и тд. ошибка похода в БД легко обработается и ответим соответствующим статусом клиентской стороне

2024-04-22 15:39 UTC, artemovechkin commented on Internal/core/entity.go
> +package core
пакет internal с маленькой буквы, чтобы компилятор распознал как внутренний пакет

2024-04-22 15:39 UTC, artemovechkin commented on Internal/handlers/products.go
> +func (m *DBMarketPlace) DeleteProduct(c *gin.Context)  {}
ожидаю реализации :)

2024-04-22 15:39 UTC, artemovechkin commented on Internal/handlers/products.go
> +}
поле MarketPlace планируется использовать под что?
если как некий кэш пользователей покупок и тд, исходя из описании структуры в пакете core, то окей, посмотрим на реализацию

рекомендую тогда обратить снимание на наполнение кэша (походом в БД) при старте приложения

2024-04-22 15:39 UTC, artemovechkin commented on Internal/handlers/products.go
> +		c.JSON(http.StatusOK, gin.H{"message": "task created"})
успешным будет 201 статус для post

2024-04-25 08:31 UTC, bmv-git commented on Internal/handlers/products.go
> +		c.JSON(http.StatusOK, gin.H{"message": "task created"})
исправил:		c.JSON(http.StatusCreated, gin.H{"message": "task created"})

2024-04-25 08:35 UTC, bmv-git commented on Internal/core/entity.go
> +package core
странно, наверно привычка начинать предложение с большой буквы) исправил

2024-04-25 08:40 UTC, bmv-git commented on Internal/core/interface.go
> +}
но файл пока не убираю - посмотрим

2024-04-30 14:50 UTC, bmv-git commented on Internal/handlers/products.go
> +}
пока сделал проще, без MarketPlace, но про кэш еще подумаю)

2024-05-02 11:29 UTC, artemovechkin reviewed
Продолжайте, все получится!

2024-05-02 11:30 UTC, artemovechkin approved these changes

2024-05-02 12:10 UTC, merged